/* Generated by Nimrod Compiler v0.9.4 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -I"c:\Program Files (x86)\Nimrod\lib" -o f:\git\nimrod-bigint\nimcache\parseutils.o f:\git\nimrod-bigint\nimcache\parseutils.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <string.h>
typedef struct tslice80291 tslice80291;
struct  tslice80291  {
NI A;
NI B;
};
static N_INLINE(void, HEX2AHEX3D_86724)(NF* x_86730, NF y_86733);
static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void, popFrame)(void);
static N_INLINE(tslice80291, HEX2EHEX2E_87222)(NI a_87226, NI b_87228);
extern TFrame* frameptr_13038;

static N_INLINE(void, nimFrame)(TFrame* s) {
	(*s).prev = frameptr_13038;
	frameptr_13038 = s;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_13038 = (*frameptr_13038).prev;
}

static N_INLINE(void, HEX2AHEX3D_86724)(NF* x_86730, NF y_86733) {
	nimfr("*=", "system.nim")
	nimln(2713, "system.nim");
	nimln(2713, "system.nim");
	(*x_86730) = ((NF)((*x_86730)) * (NF)(y_86733));
	popFrame();
}

static N_INLINE(tslice80291, HEX2EHEX2E_87222)(NI a_87226, NI b_87228) {
	tslice80291 result;
	nimfr("..", "system.nim")
	memset((void*)&result, 0, sizeof(result));
	nimln(179, "system.nim");
	result.A = a_87226;
	nimln(180, "system.nim");
	result.B = b_87228;
	popFrame();
	return result;
}
N_NOINLINE(void, parseutilsInit)(void) {
	nimfr("parseutils", "parseutils.nim")
	popFrame();
}

N_NOINLINE(void, parseutilsDatInit)(void) {
}

