/* Generated by Nimrod Compiler v0.9.4 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   "C:\Program Files (x86)\Nimrod\dist\mingw\bin\gcc.exe" -c  -w  -I"C:\Program Files (x86)\Nimrod\lib" -o c:\users\brnedan\documents\github\nimrod-bigint\nimcache\test.o c:\users\brnedan\documents\github\nimrod-bigint\nimcache\test.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <stdio.h>

#include <string.h>
typedef struct bigint85005 bigint85005;
typedef struct bigintdigits85003 bigintdigits85003;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct NimStringDesc NimStringDesc;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  bigint85005  {
bigintdigits85003* Digits;
NIM_BOOL Neg;
};
typedef N_NIMCALL_PTR(void, TY2289) (void* p, NI op);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY2289 marker;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct bigintdigits85003 {
  TGenericSeq Sup;
  NU32 data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, initbigint_85015)(NU32 val, bigint85005* Result);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(NimStringDesc*, HEX24_85508)(bigint85005 a);
N_NIMCALL(void, mod_85497)(bigint85005 a, bigint85005 b, bigint85005* Result);
static N_INLINE(void, initStackBottom)(void);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void, popFrame)(void);
N_NOINLINE(void, systemInit)(void);
N_NOINLINE(void, systemDatInit)(void);
N_NOINLINE(void, unsignedInit)(void);
N_NOINLINE(void, unsignedDatInit)(void);
N_NOINLINE(void, bigintInit)(void);
N_NOINLINE(void, bigintDatInit)(void);
N_NOINLINE(void, testInit)(void);
N_NOINLINE(void, testDatInit)(void);
bigint85005 a_86003;
extern TNimType NTI85005; /* BigInt */
bigint85005 b_86007;
extern TFrame* frameptr_13038;

static N_INLINE(void, initStackBottom)(void) {
	void* volatile locals;
	locals = 0;
	locals = ((void*) (&locals));
	setStackBottom(locals);
}
void PreMain() {
	systemDatInit();
	systemInit();
	unsignedDatInit();
	bigintDatInit();
	testDatInit();
	initStackBottom();
	unsignedInit();
	bigintInit();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMain)(void) {
	PreMain();
	testInit();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}


static N_INLINE(void, nimFrame)(TFrame* s) {
	(*s).prev = frameptr_13038;
	frameptr_13038 = s;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_13038 = (*frameptr_13038).prev;
}
N_NOINLINE(void, testInit)(void) {
	bigint85005 LOC1;
	NimStringDesc* LOC2;
	nimfr("test", "test.nim")
	nimln(3, "test.nim");
	chckNil((void*)&a_86003);
	genericReset((void*)&a_86003, (&NTI85005));
	initbigint_85015(((NU32) 100), &a_86003);
	nimln(4, "test.nim");
	chckNil((void*)&b_86007);
	genericReset((void*)&b_86007, (&NTI85005));
	initbigint_85015(((NU32) 123), &b_86007);
	nimln(6, "test.nim");
	nimln(6, "test.nim");
	nimln(6, "test.nim");
	memset((void*)&LOC1, 0, sizeof(LOC1));
	mod_85497(b_86007, a_86003, &LOC1);
	LOC2 = 0;
	LOC2 = HEX24_85508(LOC1);
	printf("%s\015\012", (LOC2)->data);
	popFrame();
}

N_NOINLINE(void, testDatInit)(void) {
}

