/* Generated by Nimrod Compiler v0.9.4 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -I"c:\Program Files (x86)\Nimrod\lib" -o f:\git\nimrod-bigint\nimcache\unsigned.o f:\git\nimrod-bigint\nimcache\unsigned.c */
#define NIM_INTBITS 64
#include "nimbase.h"
static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void, popFrame)(void);
extern TFrame* frameptr_13038;

static N_INLINE(void, nimFrame)(TFrame* s) {
	(*s).prev = frameptr_13038;
	frameptr_13038 = s;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_13038 = (*frameptr_13038).prev;
}
N_NOINLINE(void, unsignedInit)(void) {
	nimfr("unsigned", "unsigned.nim")
	popFrame();
}

N_NOINLINE(void, unsignedDatInit)(void) {
}

